# Arboles de Decision Parte 2

* Sobreajuste en los árboles de decisión
* Poda de árboles de decisión
* Simplificación de árboles de decisión mediante poda (algoritmo C4.5)
* Algoritmo CART
* Ejemplos prácticos

### Sobreajuste en los árboles de decisión

![Overfitting](https://th.bing.com/th/id/R.5eb443c8ed7b35464b02a1da6087c5a7?rik=5suy7VEr1BDSpg&pid=ImgRaw&r=0&sres=1&sresct=1)

### Poda de árboles de decisión

![Poda](https://th.bing.com/th/id/R.9b1cd84213c7057f0c93e2003ef41138?rik=vLtyz4SG4GUAsA&pid=ImgRaw&r=0&sres=1&sresct=1)

### Simplificación de árboles de decisión mediante poda (algoritmo C4.5)

![C4.5](https://www.researchgate.net/publication/319475730/figure/fig2/AS:535048409812992@1504576889684/Figura-2-Arvore-de-decisao-utilizando-o-algoritmo-C45.png)

### Algoritmo CART

![CART](CART.png)

### Ejemplos prácticos

#### Caso 1: Clasificación

In [1]:
import pandas as pd
import numpy as np

In [ ]:
clasificacion = pd.read_csv("./Data/ML-MATT-CompetitionQT2021_train.csv", sep = ";")
clasificacion.head()

,Time,CellName,PRBUsageUL,PRBUsageDL,meanThr_DL,meanThr_UL,maxThr_DL,maxThr_UL,meanUE_DL,meanUE_UL,maxUE_DL,maxUE_UL,maxUE_UL+DL,Unusual
0,10:45,3BLTE,12.3848,1.4019,0.3927,0.0438,16.6522,0.6806,1.1293,1.0491,5,3,8,1
1,9:45,1BLTE,22.0438,2.0016,0.5620,0.2697,10.3994,1.1771,1.4480,1.1630,6,5,11,1
2,7:45,9BLTE,0.5105,0.4258,0.0152,0.0106,0.2755,0.1685,1.0379,1.0535,1,2,3,1
3,2:45,4ALTE,1.9963,1.1513,0.9908,0.0245,64.7465,0.8747,1.0766,1.0526,3,2,5,1
4,3:30,10BLTE,0.3030,0.4040,0.0160,0.0130,0.3480,0.1680,1.0110,1.0110,2,1,3,0

In [3]:
data = clasificacion[['PRBUsageUL', 'PRBUsageDL', 'meanThr_DL',
       'meanThr_UL', 'maxThr_DL', 'maxThr_UL', 'meanUE_DL', 'meanUE_UL',
       'maxUE_DL', 'maxUE_UL', 'maxUE_UL+DL', 'Unusual']]
data.head()

,PRBUsageUL,PRBUsageDL,meanThr_DL,meanThr_UL,maxThr_DL,maxThr_UL,meanUE_DL,meanUE_UL,maxUE_DL,maxUE_UL,maxUE_UL+DL,Unusual
0,12.3848,1.4019,0.3927,0.0438,16.6522,0.6806,1.1293,1.0491,5,3,8,1
1,22.0438,2.0016,0.5620,0.2697,10.3994,1.1771,1.4480,1.1630,6,5,11,1
2,0.5105,0.4258,0.0152,0.0106,0.2755,0.1685,1.0379,1.0535,1,2,3,1
3,1.9963,1.1513,0.9908,0.0245,64.7465,0.8747,1.0766,1.0526,3,2,5,1
4,0.3030,0.4040,0.0160,0.0130,0.3480,0.1680,1.0110,1.0110,2,1,3,0

In [4]:
x_data = data[['PRBUsageUL', 'PRBUsageDL', 'meanThr_DL',
       'meanThr_UL', 'maxThr_DL', 'maxThr_UL', 'meanUE_DL', 'meanUE_UL',
       'maxUE_DL', 'maxUE_UL', 'maxUE_UL+DL']]

In [5]:
y_data = data["Unusual"]

In [6]:
data["Unusual"].value_counts()

0    26721
1    10183
Name: Unusual, dtype: int64

In [7]:
x_data.shape

(36904, 11)

In [8]:
y_data.shape

(36904,)

In [9]:
y_data.head()

0    1
1    1
2    1
3    1
4    0
Name: Unusual, dtype: int64

In [11]:
from sklearn.model_selection import train_test_split

In [12]:
x_train, x_test, y_train, y_test = train_test_split(x_data, y_data, test_size = 0.2, random_state = 1000)

In [13]:
x_train.shape

(29523, 11)

In [14]:
x_test.shape

(7381, 11)

In [15]:
x_test.shape[0] / x_data.shape[0]

0.20000541946672448

In [16]:
x_train

,PRBUsageUL,PRBUsageDL,meanThr_DL,meanThr_UL,maxThr_DL,maxThr_UL,meanUE_DL,meanUE_UL,maxUE_DL,maxUE_UL,maxUE_UL+DL
26132,9.8020,1.1120,0.2880,0.0240,10.9870,0.2940,1.0710,1.0210,3,2,5
9784,3.9410,1.0110,0.2270,0.0310,10.1730,0.5300,1.0610,1.0210,4,2,6
6170,0.4040,0.4040,0.0600,0.0130,3.6050,0.2950,1.0110,1.0110,2,1,3
29565,5.4653,0.7206,0.1686,0.0187,15.5143,0.3907,1.0390,1.0567,3,2,5
10595,1.1120,2.1220,0.4320,0.0420,19.9180,0.7560,1.1010,0.0100,3,3,6
...,...,...,...,...,...,...,...,...,...,...,...
33537,3.1330,8.9930,0.9740,0.0880,21.9590,0.6690,1.4350,0.0100,7,4,11
18782,6.7700,1.6170,0.1670,0.0430,4.5530,0.9470,1.1620,1.0510,4,3,7
3776,2.4250,17.2800,1.0550,0.0630,21.1870,0.7750,1.4350,0.0100,6,4,10
6215,9.6177,1.7333,0.4685,0.0306,30.9606,0.7054,1.1074,1.0515,5,3,8
4695,29.5070,11.6210,5.7430,0.2600,38.3920,1.2920,1.6980,1.5760,7,7,14

In [17]:
from sklearn.tree import DecisionTreeClassifier

In [18]:
arb_dec_cla = DecisionTreeClassifier(criterion = "gini", splitter = "best", max_depth = 6, random_state = 1000)
arb_dec_cla.fit(x_train, y_train)

DecisionTreeClassifier(max_depth=6, random_state=1000)

In [19]:
y_pred_adc = arb_dec_cla.predict(x_test)
y_pred_adc

array([1, 0, 1, ..., 0, 0, 0], dtype=int64)

In [20]:
from sklearn.metrics import confusion_matrix
from sklearn.metrics import accuracy_score
from sklearn.metrics import precision_score
from sklearn.metrics import recall_score
from sklearn.metrics import f1_score
from sklearn.metrics import roc_auc_score

print(confusion_matrix(y_pred_adc, y_test))
print(accuracy_score(y_pred_adc, y_test))
print(precision_score(y_pred_adc, y_test))
print(recall_score(y_pred_adc, y_test))
print(f1_score(y_pred_adc, y_test))
print(roc_auc_score(y_pred_adc, y_test))

[[5284  774]
 [  53 1270]]
0.887955561577022
0.6213307240704501
0.9599395313681028
0.7543807543807544
0.9160872962221828

In [21]:
(5284 + 1270)

6554

In [22]:
confusion_matrix(y_test, y_pred_adc).sum().sum()

7381

In [23]:
6554/7381

0.887955561577022

In [24]:
arb_dec_cla_2 = DecisionTreeClassifier(criterion = "entropy", splitter = "best", max_depth = 8, random_state = 1000)
arb_dec_cla_2.fit(x_train, y_train)

DecisionTreeClassifier(criterion='entropy', max_depth=8, random_state=1000)

In [25]:
y_pred_adc_2 = arb_dec_cla_2.predict(x_test)
y_pred_adc_2

array([1, 0, 1, ..., 0, 0, 0], dtype=int64)

In [26]:
print(confusion_matrix(y_pred_adc_2, y_test))
print(accuracy_score(y_pred_adc_2, y_test))
print(precision_score(y_pred_adc_2, y_test))
print(recall_score(y_pred_adc_2, y_test))
print(f1_score(y_pred_adc_2, y_test))
print(roc_auc_score(y_pred_adc_2, y_test))

[[5271  664]
 [  66 1380]]
0.9010974122747595
0.675146771037182
0.9543568464730291
0.7908309455587393
0.9212390803553014

In [27]:
5271 + 1380

6651

In [28]:
from graphviz import Source
from sklearn.tree import export_graphviz

In [29]:
export_graphviz(
        arb_dec_cla_2,
        out_file = "arbol_2.dot",
        feature_names = x_train.columns.to_numpy(), # Nombres de las caracteristicas
        class_names = ["1", "0"], # Nombre de los grupos
        rounded = True,
        filled = True)

In [ ]:
Source.from_file("arbol_1.dot")

#### Caso 2: Regresión

In [ ]:
regresion = pd.read_csv("./Data/House_Prices_train.csv")
regresion.head()

,Id,MSSubClass,LotFrontage,LotArea,OverallQual,OverallCond,YearBuilt,YearRemodAdd,MasVnrArea,BsmtFinSF1,...,WoodDeckSF,OpenPorchSF,EnclosedPorch,3SsnPorch,ScreenPorch,PoolArea,MiscVal,MoSold,YrSold,SalePrice
0,1,60,65.0,8450,7,5,2003,2003,196.0,706,...,0,61,0,0,0,0,0,2,2008,208500
1,2,20,80.0,9600,6,8,1976,1976,0.0,978,...,298,0,0,0,0,0,0,5,2007,181500
2,3,60,68.0,11250,7,5,2001,2002,162.0,486,...,0,42,0,0,0,0,0,9,2008,223500
3,4,70,60.0,9550,7,5,1915,1970,0.0,216,...,0,35,272,0,0,0,0,2,2006,140000
4,5,60,84.0,14260,8,5,2000,2000,350.0,655,...,192,84,0,0,0,0,0,12,2008,250000

In [31]:
x_data = regresion[['MSSubClass', 'LotArea', 'OverallQual',
       'OverallCond', 'YearBuilt', 'YearRemodAdd', 'BsmtFinSF1',
       'BsmtFinSF2', 'BsmtUnfSF', 'TotalBsmtSF', '1stFlrSF', '2ndFlrSF',
       'LowQualFinSF', 'GrLivArea', 'BsmtFullBath', 'BsmtHalfBath', 'FullBath',
       'HalfBath', 'BedroomAbvGr', 'KitchenAbvGr', 'TotRmsAbvGrd',
       'Fireplaces', 'GarageCars', 'GarageArea', 'WoodDeckSF',
       'OpenPorchSF', 'EnclosedPorch', '3SsnPorch', 'ScreenPorch', 'PoolArea',
       'MiscVal', 'MoSold', 'YrSold']]

In [32]:
y_data = regresion["SalePrice"]

In [33]:
x0_train, x0_test, y0_train, y0_test = train_test_split(x_data, y_data, test_size = 0.2, random_state = 1000)

In [34]:
from sklearn.tree import DecisionTreeRegressor

In [35]:
arb_dec_reg = DecisionTreeRegressor(criterion = "squared_error", splitter = "best", max_depth = 9, random_state = 1000)
arb_dec_reg.fit(x0_train, y0_train)

DecisionTreeRegressor(max_depth=9, random_state=1000)

In [36]:
y0_predict_adr = arb_dec_reg.predict(x0_test)
y0_predict_adr

array([ 93826.74358974, 159815.38461538, 152414.28571429, 170713.875     ,
       139062.5       , 160224.35      , 274500.        ,  93826.74358974,
       148450.        ,  96750.        , 108194.11764706, 140000.        ,
       223500.        ,  93826.74358974, 203770.        , 129754.54545455,
       148450.        , 152414.28571429, 135905.35714286,  93826.74358974,
       124288.        , 223200.        ,  66842.85714286, 155000.        ,
       129754.54545455, 311660.        , 373279.94117647, 168833.33333333,
       151400.        , 144842.5       , 129754.54545455, 193607.3875    ,
       125500.        , 203770.        , 193607.3875    , 137893.10344828,
       129754.54545455, 306000.        , 270000.        , 148450.        ,
       129754.54545455, 148450.        ,  93826.74358974, 290000.        ,
       193607.3875    , 129754.54545455, 234539.33333333, 437154.        ,
       129754.54545455, 120650.        , 101392.70588235, 311660.        ,
       117291.51851852, 137500.        , 101392.70588235, 147614.28571429,
       147614.28571429,  66842.85714286,  93826.74358974, 178383.5       ,
       124046.25641026, 170713.875     , 222295.        , 137893.10344828,
       174680.        , 215081.57894737, 136000.        , 231642.85714286,
       147614.28571429, 178383.5       , 208100.        , 181933.33333333,
       108194.11764706, 424870.        , 124288.        , 276713.68421053,
       144842.5       , 240614.77272727, 120864.95833333, 178383.5       ,
       147614.28571429, 144842.5       , 174680.        , 148450.        ,
       139062.5       , 136000.        , 193607.3875    , 215081.57894737,
       141500.        , 203770.        , 451950.        , 178383.5       ,
       135905.35714286, 139062.5       , 182262.33333333,  93826.74358974,
       437154.        , 215081.57894737, 244400.        , 333200.        ,
       108194.11764706, 147614.28571429, 162500.        , 164750.        ,
       193607.3875    , 179757.14285714, 139472.72727273, 311660.        ,
       181933.33333333, 222295.        , 148450.        , 124288.        ,
       229456.        , 174680.        , 145000.        , 129754.54545455,
       373201.        , 306928.25      , 124046.25641026, 159815.38461538,
       182262.33333333, 159500.        , 203770.        , 148000.        ,
       137893.10344828, 244400.        , 147614.28571429, 215081.57894737,
       318000.        , 193607.3875    , 129754.54545455, 120864.95833333,
       137893.10344828, 244400.        , 193607.3875    , 165000.        ,
        82833.33333333, 182262.33333333, 129754.54545455, 108194.11764706,
       129754.54545455, 285000.        , 152414.28571429, 124288.        ,
       124046.25641026,  83342.85714286, 137893.10344828, 137893.10344828,
       160224.35      , 193607.3875    , 142883.33333333, 162115.        ,
       178383.5       , 234539.33333333, 124046.25641026, 383970.        ,
       178383.5       , 179757.14285714,  93826.74358974, 162115.        ,
       159815.38461538, 182714.28571429,  83342.85714286, 170713.875     ,
       241500.        , 265656.91666667, 164900.        , 170713.875     ,
       100000.        ,  62383.        , 206013.63636364,  93826.74358974,
       124046.25641026, 311500.        , 187500.        , 373279.94117647,
        66842.85714286, 137893.10344828, 178383.5       , 173733.        ,
       240614.77272727, 165990.        ,  84500.        ,  83342.85714286,
       137893.10344828, 130225.        , 338000.        , 108194.11764706,
       144842.5       , 193607.3875    , 101392.70588235, 373201.        ,
       142883.33333333, 279500.        , 124288.        , 178383.5       ,
       148450.        , 124288.        , 170713.875     , 206013.63636364,
       162115.        , 383970.        , 129754.54545455, 193607.3875    ,
       131297.61904762, 193607.3875    , 373279.94117647, 124046.25641026,
       306928.25      , 101392.70588235, 136755.28571429, 383970.        ,
        82833.33333333, 101392.70588235,  82833.33333333, 130225.        ,
       144842.5       , 139472.72727273, 137893.10344828, 193607.3875    ,
       311660.        , 148450.        , 108194.11764706, 189035.        ,
       193607.3875    , 302000.        , 101392.70588235, 254750.        ,
       181933.33333333, 124046.25641026,  82833.33333333, 170166.66666667,
       240614.77272727,  83342.85714286, 240614.77272727, 306928.25      ,
       206250.        , 538000.        , 412500.        , 193607.3875    ,
       124288.        , 117291.51851852, 611657.        , 170713.875     ,
       234539.33333333, 139472.72727273, 200624.        , 142883.33333333,
        82833.33333333, 140000.        , 177082.5       , 117291.51851852,
        81333.33333333, 234539.33333333, 240614.77272727, 129754.54545455,
       193607.3875    , 311660.        , 154166.66666667, 124288.        ,
       124288.        , 135905.35714286, 311660.        , 117291.51851852,
       237112.5       , 139062.5       , 193607.3875    , 276713.68421053,
       155000.        , 124046.25641026, 147614.28571429, 133900.        ,
       113000.        , 129754.54545455, 167000.        , 276713.68421053,
        66842.85714286, 115000.        , 373279.94117647, 125500.        ,
        93826.74358974, 139062.5       , 274725.        , 274900.        ,
       124288.        , 285000.        , 124288.        , 108194.11764706,
       193607.3875    , 162115.        , 206013.63636364, 122750.        ])

In [37]:
from sklearn.metrics import mean_squared_error

In [38]:
mean_squared_error(y0_test, y0_predict_adr)

1704899768.3071747

In [39]:
arb_dec_reg_2 = DecisionTreeRegressor(criterion = "friedman_mse", splitter = "random", max_depth = 9, random_state = 1000)
arb_dec_reg_2.fit(x0_train, y0_train)

DecisionTreeRegressor(criterion='friedman_mse', max_depth=9, random_state=1000,
                      splitter='random')

In [40]:
y0_predict_adr_2 = arb_dec_reg_2.predict(x0_test)
y0_predict_adr_2

array([119403.        , 160167.125     , 188700.        , 180296.16666667,
       149095.37037037, 150000.        , 248750.        , 136101.08695652,
       125833.33333333, 153000.        , 149095.37037037, 132330.        ,
       318061.        ,  97987.5       , 225893.19148936, 119403.        ,
       123500.        , 158160.71428571, 159916.66666667,  97987.5       ,
       119403.        , 174273.80952381,  81322.22222222, 180296.16666667,
       119403.        , 245707.95      , 388523.76923077, 149095.37037037,
       200100.        , 132330.        , 119403.        , 194528.21428571,
       137766.91176471, 225893.19148936, 180296.16666667, 147388.88888889,
       119403.        , 313996.23529412, 280000.        , 197500.        ,
       119403.        , 149095.37037037, 149095.37037037, 412500.        ,
       180296.16666667, 119403.        , 225893.19148936, 315000.        ,
       119403.        , 101000.        ,  95616.66666667, 444552.        ,
       119403.        , 194528.21428571,  93000.        , 149095.37037037,
       149095.37037037,  55000.        , 137766.91176471, 233712.85714286,
       118906.66666667, 137766.91176471, 180296.16666667, 147388.88888889,
       179100.        , 245707.95      , 161000.        , 218953.46666667,
       149095.37037037, 180296.16666667, 203780.        , 140000.        ,
       132330.        , 444552.        , 119403.        , 283775.        ,
       179200.        , 245707.95      , 155877.77777778, 180296.16666667,
       135000.        , 174500.        , 165500.        , 155877.77777778,
       137766.91176471, 133440.38461538, 180296.16666667, 161750.        ,
       132330.        , 225893.19148936, 334288.2       , 180296.16666667,
       141000.        , 189950.        , 180296.16666667,  90833.33333333,
       392000.        , 313996.23529412, 233712.85714286, 313996.23529412,
       120600.        , 149095.37037037, 180296.16666667, 180296.16666667,
       194528.21428571, 211812.        , 125181.25      , 475000.        ,
       241500.        , 180296.16666667, 149095.37037037, 136101.08695652,
       241208.        , 203780.        , 137766.91176471, 119403.        ,
       285000.        , 245707.95      ,  81666.66666667, 133440.38461538,
       180296.16666667, 225893.19148936, 193500.        , 149095.37037037,
       149095.37037037, 245707.95      , 149095.37037037, 245707.95      ,
       313996.23529412, 180296.16666667,  90595.45454545, 129944.27272727,
       149095.37037037, 325000.        , 180296.16666667, 180296.16666667,
        81322.22222222, 180296.16666667, 119403.        , 109813.33333333,
       133524.03846154, 283775.        , 125333.33333333, 119403.        ,
       118906.66666667,  58500.        , 149095.37037037, 136101.08695652,
       133440.38461538, 313996.23529412, 137766.91176471, 149095.37037037,
       180296.16666667, 225893.19148936, 117501.        , 328000.        ,
       299800.        , 166133.33333333,  90595.45454545, 161750.        ,
       214500.        , 194528.21428571, 104821.23076923, 180296.16666667,
       180296.16666667, 304091.5       , 150000.        , 158160.71428571,
       108500.        , 119403.        , 225893.19148936,  90833.33333333,
        90833.33333333, 194528.21428571, 241208.        , 313996.23529412,
        72500.        , 162033.33333333, 180296.16666667, 180296.16666667,
       245707.95      , 149095.37037037, 149095.37037037,  98000.        ,
       136101.08695652, 167500.        , 313996.23529412, 120600.        ,
       147388.88888889, 194528.21428571, 104821.23076923, 313996.23529412,
       120409.375     , 245707.95      , 147388.88888889, 180296.16666667,
       147388.88888889, 147500.        , 248750.        , 136101.08695652,
       165500.        , 296000.        , 133524.03846154, 180296.16666667,
       136101.08695652, 180296.16666667, 555000.        , 133440.38461538,
       304091.5       , 109813.33333333, 118906.66666667, 258755.33333333,
        72500.        , 133440.38461538,  81322.22222222, 133524.03846154,
       150000.        , 139600.        , 136101.08695652, 149095.37037037,
       317285.71428571, 149095.37037037, 125181.25      , 133440.38461538,
       313996.23529412, 137766.91176471, 109813.33333333, 169087.5       ,
       125333.33333333, 118906.66666667,  81322.22222222, 149095.37037037,
       245707.95      ,  87000.        , 245707.95      , 229592.46666667,
       256000.        , 412500.        , 412500.        , 180296.16666667,
       147500.        , 125166.66666667, 388523.76923077, 158160.71428571,
       245707.95      , 137766.91176471, 136101.08695652, 104821.23076923,
        72500.        , 125181.25      , 174273.80952381, 103000.        ,
        81666.66666667, 233712.85714286, 180296.16666667, 119403.        ,
       180296.16666667, 304091.5       , 129000.        , 136101.08695652,
       119403.        , 143000.        , 245707.95      , 119403.        ,
       193070.        , 147388.88888889, 180296.16666667, 283775.        ,
       180296.16666667, 159916.66666667, 160167.125     , 250000.        ,
       120409.375     , 119403.        , 263000.        , 283775.        ,
        81322.22222222, 104821.23076923, 372397.        , 135000.        ,
       106500.        , 133440.38461538, 245707.95      , 395192.        ,
       118906.66666667, 283775.        , 119403.        , 107000.        ,
       194528.21428571, 174273.80952381, 137766.91176471, 129944.27272727])

In [41]:
mean_squared_error(y0_test, y0_predict_adr_2)

1426766686.8420389

In [42]:
mean_squared_error(y0_test, y0_predict_adr) # Primer modelo (mse)

1704899768.3071747

In [43]:
mean_squared_error(y0_test, y0_predict_adr_2) # Segundo modelo (friedman mse)

1426766686.8420389