In [1]:
import pandas as pd
from mlxtend.frequent_patterns import apriori
from mlxtend.preprocessing import TransactionEncoder
from mlxtend.frequent_patterns import association_rules

In [2]:
url = (
    "https://raw.githubusercontent.com/JoaquinAmatRodrigo/Estadistica-con-R/"
    "master/datos/datos_groceries.csv"
)
datos = pd.read_csv(url)
datos.head()

   id_compra                 item
0          1         citrus fruit
1          1  semi-finished bread
2          1            margarine
3          1          ready soups
4          2       tropical fruit

In [3]:
datos["id_compra"].nunique()

9835

In [4]:
datos["item"].nunique()

169

In [5]:
datos.shape

(43367, 2)

In [6]:
# Crear una lista de listas que contenga los ítems de cada transacción
transacciones = datos.groupby("id_compra")["item"].apply(list).to_list()

# Entrenar el objeto TransactionEncoder y transformar los datos
encoder = TransactionEncoder()
transacciones_encoded = encoder.fit(transacciones).transform(transacciones)
transacciones_encoded = pd.DataFrame(transacciones_encoded, columns=encoder.columns_)
transacciones_encoded.head(10)

,Instant food products,UHT-milk,abrasive cleaner,artif. sweetener,baby cosmetics,baby food,bags,baking powder,bathroom cleaner,beef,...,turkey,vinegar,waffles,whipped/sour cream,whisky,white bread,white wine,whole milk,yogurt,zwieback
0,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,True,False
2,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,True,False,False
3,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,True,False
4,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,True,False,False
5,False,False,True,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,True,True,False
6,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
7,False,True,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
8,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
9,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,True,False,False

In [7]:
transacciones_encoded.shape

(9835, 169)

In [8]:
transacciones

[['citrus fruit', 'semi-finished bread', 'margarine', 'ready soups'],
 ['tropical fruit', 'yogurt', 'coffee'],
 ['whole milk'],
 ['pip fruit', 'yogurt', 'cream cheese', 'meat spreads'],
 ['other vegetables',
  'whole milk',
  'condensed milk',
  'long life bakery product'],
 ['whole milk', 'butter', 'yogurt', 'rice', 'abrasive cleaner'],
 ['rolls/buns'],
 ['other vegetables',
  'UHT-milk',
  'rolls/buns',
  'bottled beer',
  'liquor (appetizer)'],
 ['pot plants'],
 ['whole milk', 'cereals'],
 ['tropical fruit',
  'other vegetables',
  'white bread',
  'bottled water',
  'chocolate'],
 ['citrus fruit',
  'tropical fruit',
  'whole milk',
  'butter',
  'curd',
  'yogurt',
  'flour',
  'bottled water',
  'dishes'],
 ['beef'],
 ['frankfurter', 'rolls/buns', 'soda'],
 ['chicken', 'tropical fruit'],
 ['butter', 'sugar', 'fruit/vegetable juice', 'newspapers'],
 ['fruit/vegetable juice'],
 ['packaged fruit/vegetables'],
 ['chocolate'],
 ['specialty bar'],
 ['other vegetables'],
 ['butter milk', 'pastry'],
 ['whole milk'],
 ['tropical fruit',
  'cream cheese',
  'processed cheese',
  'detergent',
  'newspapers'],
 ['tropical fruit',
  'root vegetables',
  'other vegetables',
  'frozen dessert',
  'rolls/buns',
  'flour',
  'sweet spreads',
  'salty snack',
  'waffles',
  'candy',
  'bathroom cleaner'],
 ['bottled water', 'canned beer'],
 ['yogurt'],
 ['sausage', 'rolls/buns', 'soda', 'chocolate'],
 ['other vegetables'],
 ['brown bread',
  'soda',
  'fruit/vegetable juice',
  'canned beer',
  'newspapers',
  'shopping bags'],
 ['yogurt', 'beverages', 'bottled water', 'specialty bar'],
 ['hamburger meat',
  'other vegetables',
  'rolls/buns',
  'spices',
  'bottled water',
  'hygiene articles',
  'napkins'],
 ['root vegetables', 'other vegetables', 'whole milk', 'beverages', 'sugar'],
 ['pork',
  'berries',
  'other vegetables',
  'whole milk',
  'whipped/sour cream',
  'artif. sweetener',
  'soda',
  'abrasive cleaner'],
 ['beef', 'grapes', 'detergent'],
 ['pastry', 'soda'],
 ['fruit/vegetable juice'],
 ['canned beer'],
 ['root vegetables', 'other vegetables', 'whole milk', 'dessert'],
 ['citrus fruit', 'zwieback', 'newspapers'],
 ['sausage',
  'rolls/buns',
  'soda',
  'canned beer',
  'specialty bar',
  'shopping bags'],
 ['tropical fruit',
  'root vegetables',
  'whole milk',
  'yogurt',
  'domestic eggs',
  'brown bread',
  'pastry',
  'sugar',
  'cereals',
  'coffee',
  'soda',
  'waffles',
  'candy'],
 ['berries', 'yogurt'],
 ['canned beer'],
 ['butter milk',
  'yogurt',
  'cream cheese',
  'spread cheese',
  'rolls/buns',
  'bottled water',
  'soda',
  'newspapers'],
 ['coffee'],
 ['pastry', 'bottled water'],
 ['rolls/buns'],
 ['misc. beverages'],
 ['root vegetables',
  'other vegetables',
  'butter',
  'curd',
  'whipped/sour cream',
  'UHT-milk',
  'hard cheese',
  'rolls/buns',
  'bottled water',
  'long life bakery product'],
 ['sausage', 'rolls/buns', 'cat food', 'newspapers'],
 ['canned beer'],
 ['ham', 'grapes', 'other vegetables', 'whole milk'],
 ['turkey',
  'tropical fruit',
  'other vegetables',
  'curd',
  'domestic eggs',
  'brown bread',
  'semi-finished bread',
  'margarine',
  'baking powder',
  'fruit/vegetable juice'],
 ['whole milk', 'yogurt', 'processed cheese', 'pickled vegetables', 'soda'],
 ['whole milk', 'curd', 'yogurt', 'pastry'],
 ['packaged fruit/vegetables', 'brown bread', 'canned beer'],
 ['rolls/buns',
  'oil',
  'bottled water',
  'chewing gum',
  'chocolate marshmallow',
  'hygiene articles',
  'napkins'],
 ['ham', 'beef', 'whipped/sour cream', 'ice cream', 'rolls/buns', 'cat food'],
 ['rolls/buns', 'pastry', 'sugar'],
 ['other vegetables',
  'whole milk',
  'frozen vegetables',
  'canned fish',
  'salty snack',
  'seasonal products',
  'detergent'],
 ['sausage', 'pastry'],
 ['sausage', 'beef', 'whole milk'],
 ['frankfurter', 'tropical fruit', 'rolls/buns', 'brown bread', 'sugar'],
 ['rolls/buns', 'pastry', 'soda'],
 ['whole milk'],
 ['curd cheese', 'coffee'],
 ['red/blush wine', 'newspapers'],
 ['sausage', 'whole milk', 'curd'],
 ['tropical fruit',
  'pip fruit',
  'berries',
  'whole milk',
  'frozen potato products',
  'rolls/buns',
  'pickled vegetables',
  'chocolate'],
 ['red/blush wine'],
 ['whole milk',
  'butter',
  'margarine',
  'specialty fat',
  'specialty chocolate',
  'candles',
  'flower (seeds)'],
 ['frankfurter',
  'citrus fruit',
  'whole milk',
  'domestic eggs',
  'oil',
  'sparkling wine',
  'specialty chocolate',
  'newspapers'],
 ['whole milk', 'meat spreads', 'soda'],
 ['frozen potato products'],
 ['other vegetables', 'whole milk', 'rolls/buns', 'sugar'],
 ['citrus fruit', 'whole milk', 'curd', 'butter milk', 'pastry'],
 ['flour', 'salt', 'bottled water', 'fruit/vegetable juice', 'bottled beer'],
 ['sugar', 'bottled water', 'soda', 'bottled beer'],
 ['frozen meals', 'coffee'],
 ['chocolate'],
 ['root vegetables',
  'whole milk',
  'frozen vegetables',
  'domestic eggs',
  'rolls/buns',
  'oil',
  'margarine',
  'canned vegetables',
  'fruit/vegetable juice',
  'bathroom cleaner'],
 ['root vegetables', 'onions', 'hard cheese', 'frozen vegetables'],
 ['herbs',
  'condensed milk',
  'frozen vegetables',
  'salt',
  'oil',
  'white wine',
  'candles'],
 ['bottled water'],
 ['sausage',
  'root vegetables',
  'onions',
  'yogurt',
  'rolls/buns',
  'brandy',
  'detergent'],
 ['coffee', 'newspapers'],
 ['pork', 'other vegetables', 'whipped/sour cream'],
 ['berries', 'yogurt'],
 ['soda'],
 ['berries'],
 ['fruit/vegetable juice', 'salty snack', 'candles'],
 ['citrus fruit', 'butter milk', 'yogurt', 'cream cheese'],
 ['pork',
  'hamburger meat',
  'citrus fruit',
  'berries',
  'onions',
  'whipped/sour cream',
  'rice',
  'coffee',
  'chocolate'],
 ['detergent'],
 ['grapes', 'photo/film'],
 ['sausage',
  'sliced cheese',
  'rolls/buns',
  'brown bread',
  'fruit/vegetable juice',
  'canned beer',
  'red/blush wine',
  'waffles',
  'shopping bags'],
 ['chicken',
  'hamburger meat',
  'citrus fruit',
  'tropical fruit',
  'root vegetables',
  'other vegetables',
  'butter',
  'pasta',
  'oil',
  'detergent'],
 ['whole milk', 'yogurt', 'brown bread'],
 ['citrus fruit', 'tropical fruit'],
 ['soda', 'misc. beverages'],
 ['sausage',
  'pork',
  'grapes',
  'whole milk',
  'rolls/buns',
  'pastry',
  'soda',
  'specialty bar',
  'bathroom cleaner'],
 ['frankfurter', 'rolls/buns', 'bottled water'],
 ['sausage',
  'whole milk',
  'yogurt',
  'coffee',
  'fruit/vegetable juice',
  'bottled beer',
  'softener',
  'napkins',
  'photo/film',
  'shopping bags'],
 ['soda'],
 ['rolls/buns', 'fruit/vegetable juice'],
 ['beef',
  'citrus fruit',
  'berries',
  'root vegetables',
  'brown bread',
  'detergent'],
 ['whole milk',
  'whipped/sour cream',
  'rolls/buns',
  'soda',
  'waffles',
  'candy',
  'cling film/bags'],
 ['processed cheese'],
 ['tropical fruit', 'pip fruit'],
 ['frankfurter',
  'sausage',
  'root vegetables',
  'other vegetables',
  'rolls/buns',
  'oil',
  'pickled vegetables',
  'bottled beer',
  'chewing gum',
  'dishes'],
 ['packaged fruit/vegetables', 'bottled water'],
 ['whole milk',
  'dessert',
  'frozen vegetables',
  'rolls/buns',
  'margarine',
  'bottled water',
  'red/blush wine',
  'newspapers'],
 ['berries', 'whipped/sour cream'],
 ['citrus fruit', 'berries', 'UHT-milk', 'processed cheese'],
 ['tropical fruit', 'whole milk', 'yogurt'],
 ['hamburger meat',
  'whole milk',
  'frozen vegetables',
  'rolls/buns',
  'bottled beer',
  'sparkling wine'],
 ['hamburger meat',
  'other vegetables',
  'whole milk',
  'frozen vegetables',
  'domestic eggs',
  'soda',
  'dishes'],
 ['whole milk', 'cream cheese', 'soda'],
 ['fish',
  'other vegetables',
  'pastry',
  'margarine',
  'coffee',
  'long life bakery product',
  'male cosmetics',
  'shopping bags'],
 ['frankfurter', 'sausage', 'long life bakery product', 'waffles'],
 ['packaged fruit/vegetables',
  'dessert',
  'semi-finished bread',
  'canned beer'],
 ['pastry', 'soda'],
 ['other vegetables', 'red/blush wine'],
 ['misc. beverages'],
 ['frankfurter',
  'sausage',
  'citrus fruit',
  'tropical fruit',
  'pip fruit',
  'whole milk',
  'hard cheese',
  'cream cheese',
  'domestic eggs',
  'rice',
  'sugar',
  'canned fruit',
  'misc. beverages',
  'fruit/vegetable juice',
  'hygiene articles'],
 ['sparkling wine'],
 ['specialty bar'],
 ['sausage', 'butter milk', 'rolls/buns'],
 ['curd cheese'],
 ['frankfurter', 'dessert'],
 ['whole milk', 'yogurt', 'beverages', 'brown bread', 'shopping bags'],
 ['newspapers'],
 ['berries', 'soda'],
 ['curd', 'flour', 'liquor (appetizer)'],
 ['tropical fruit', 'other vegetables', 'coffee'],
 ['soda'],
 ['rolls/buns', 'Instant food products'],
 ['canned beer'],
 ['canned beer'],
 ['frankfurter', 'sausage', 'whole milk', 'rolls/buns', 'margarine'],
 ['other vegetables', 'misc. beverages', 'canned beer'],
 ['whole milk', 'frozen vegetables'],
 ['whole milk'],
 ['citrus fruit',
  'butter',
  'cream cheese',
  'white bread',
  'oil',
  'margarine',
  'newspapers'],
 ['frankfurter', 'rolls/buns'],
 ['frankfurter',
  'ham',
  'pip fruit',
  'other vegetables',
  'whole milk',
  'soft cheese',
  'frozen vegetables',
  'rolls/buns',
  'sugar',
  'baking powder'],
 ['butter milk', 'yogurt', 'honey', 'soda', 'detergent'],
 ['hamburger meat',
  'citrus fruit',
  'onions',
  'rolls/buns',
  'bottled water',
  'dental care'],
 ['pasta', 'popcorn'],
 ['other vegetables',
  'whole milk',
  'meat spreads',
  'cake bar',
  'chocolate',
  'shopping bags'],
 ['sausage',
  'pork',
  'citrus fruit',
  'dessert',
  'white bread',
  'dishes',
  'candles'],
 ['rolls/buns'],
 ['grapes', 'other vegetables', 'curd', 'dessert', 'yogurt', 'napkins'],
 ['root vegetables',
  'other vegetables',
  'whole milk',
  'yogurt',
  'beverages',
  'soft cheese',
  'frozen vegetables',
  'fruit/vegetable juice',
  'bottled beer'],
 ['coffee', 'shopping bags'],
 ['popcorn'],
 ['whole milk', 'rolls/buns', 'sugar', 'bottled water', 'soda'],
 ['tropical fruit',
  'other vegetables',
  'packaged fruit/vegetables',
  'whole milk',
  'snack products'],
 ['beef', 'herbs', 'flour', 'cling film/bags', 'flower soil/fertilizer'],
 ['whole milk', 'butter', 'dessert', 'rolls/buns'],
 ['frankfurter', 'soda', 'chewing gum'],
 ['tropical fruit', 'specialty cheese', 'bottled water'],
 ['canned beer'],
 ['finished products',
  'other vegetables',
  'frozen vegetables',
  'bottled beer'],
 ['beverages', 'soda'],
 ['hamburger meat', 'root vegetables', 'whole milk'],
 ['whole milk', 'pastry', 'long life bakery product'],
 ['finished products', 'white wine', 'shopping bags'],
 ['other vegetables'],
 ['ham',
  'tropical fruit',
  'other vegetables',
  'whole milk',
  'white bread',
  'brown bread',
  'fruit/vegetable juice',
  'bottled beer'],
 ['other vegetables'],
 ['curd', 'butter milk', 'cocoa drinks', 'salty snack', 'popcorn'],
 ['bottled beer'],
 ['curd',
  'dessert',
  'soda',
  'salty snack',
  'waffles',
  'cake bar',
  'chocolate',
  'shopping bags'],
 ['whole milk', 'cream cheese', 'cereals', 'dog food'],
 ['whole milk', 'salt'],
 ['dessert', 'ice cream'],
 ['sausage', 'soft cheese', 'coffee'],
 ['other vegetables', 'bottled water', 'waffles', 'dishes', 'shopping bags'],
 ['ham', 'whole milk', 'rolls/buns'],
 ['other vegetables', 'ice cream'],
 ['other vegetables', 'bottled water'],
 ['soda', 'bottled beer', 'white wine', 'prosecco'],
 ['herbs', 'candy'],
 ['frankfurter',
  'ham',
  'tropical fruit',
  'pip fruit',
  'root vegetables',
  'other vegetables',
  'whole milk',
  'butter',
  'curd',
  'yogurt',
  'whipped/sour cream',
  'soft cheese',
  'sliced cheese',
  'cream cheese',
  'frozen meals',
  'frozen fish',
  'domestic eggs',
  'white bread',
  'sugar',
  'cereals',
  'fruit/vegetable juice',
  'bottled beer',
  'waffles'],
 ['rolls/buns', 'canned beer'],
 ['curd',
  'cream cheese',
  'semi-finished bread',
  'zwieback',
  'cake bar',
  'specialty bar',
  'shopping bags'],
 ['frankfurter',
  'tropical fruit',
  'whole milk',
  'spread cheese',
  'margarine',
  'shopping bags'],
 ['other vegetables'],
 ['dog food'],
 ['specialty bar'],
 ['curd', 'salt', 'liquor (appetizer)', 'detergent', 'shopping bags'],
 ['frankfurter', 'rolls/buns'],
 ['soda'],
 ['beef',
  'berries',
  'root vegetables',
  'whole milk',
  'dessert',
  'spread cheese',
  'brown bread'],
 ['canned beer'],
 ['pork', 'beef', 'pip fruit', 'herbs', 'spices'],
 ['frankfurter', 'citrus fruit', 'UHT-milk', 'margarine', 'sugar'],
 ['sausage', 'bottled beer', 'liquor (appetizer)'],
 ['canned beer'],
 ['specialty chocolate'],
 ['curd', 'rolls/buns'],
 ['canned beer'],
 ['whole milk', 'bottled water', 'newspapers'],
 ['rolls/buns', 'chewing gum'],
 ['pork', 'root vegetables', 'other vegetables', 'whole milk', 'dishes'],
 ['citrus fruit', 'pastry'],
 ['pot plants'],
 ['rolls/buns', 'pastry', 'soda'],
 ['butter',
  'yogurt',
  'bottled water',
  'soda',
  'make up remover',
  'hygiene articles'],
 ['condensed milk', 'sugar', 'coffee', 'shopping bags'],
 ['sausage', 'other vegetables', 'yogurt', 'soda', 'shopping bags'],
 ['whole milk', 'beverages', 'UHT-milk', 'soda'],
 ['sausage', 'pork', 'beef', 'whole milk', 'rolls/buns', 'margarine'],
 ['beverages'],
 ['beverages', 'specialty bar'],
 ['bottled water', 'fruit/vegetable juice'],
 ['newspapers'],
 ['cleaner', 'female sanitary products'],
 ['sausage', 'soda', 'newspapers', 'shopping bags'],
 ['newspapers'],
 ['sausage',
  'beef',
  'citrus fruit',
  'other vegetables',
  'whole milk',
  'butter milk',
  'whipped/sour cream',
  'beverages',
  'hard cheese',
  'rolls/buns',
  'dish cleaner',
  'cookware'],
 ['misc. beverages', 'newspapers'],
 ['white wine'],
 ['sausage',
  'sliced cheese',
  'rolls/buns',
  'soda',
  'canned beer',
  'shopping bags'],
 ['meat', 'curd', 'bottled beer', 'cake bar'],
 ['frankfurter',
  'meat',
  'tropical fruit',
  'onions',
  'oil',
  'baking powder',
  'tea',
  'cling film/bags'],
 ['ice cream', 'rolls/buns', 'canned beer'],
 ['canned beer'],
 ['tropical fruit',
  'berries',
  'root vegetables',
  'other vegetables',
  'bottled water',
  'shopping bags'],
 ['meat',
  'citrus fruit',
  'other vegetables',
  'curd',
  'dessert',
  'butter milk',
  'beverages',
  'cream cheese',
  'rolls/buns',
  'brown bread',
  'tea',
  'bottled water'],
 ['whole milk', 'mustard', 'bottled water'],
 ['sausage',
  'beef',
  'beverages',
  'sliced cheese',
  'rolls/buns',
  'spices',
  'house keeping products',
  'flower (seeds)'],
 ['frankfurter',
  'sausage',
  'root vegetables',
  'butter',
  'curd',
  'sliced cheese',
  'rolls/buns',
  'salty snack',
  'long life bakery product'],
 ['meat', 'other vegetables', 'butter', 'rolls/buns'],
 ['root vegetables',
  'beverages',
  'Instant food products',
  'pickled vegetables',
  'detergent'],
 ['root vegetables',
  'herbs',
  'other vegetables',
  'whole milk',
  'sliced cheese',
  'rolls/buns'],
 ['whole milk', 'whipped/sour cream', 'semi-finished bread', 'margarine'],
 ['citrus fruit',
  'whole milk',
  'curd',
  'dessert',
  'yogurt',
  'whipped/sour cream',
  'frozen dessert',
  'rolls/buns',
  'salt',
  'sugar',
  'cereals',
  'canned vegetables',
  'canned fish',
  'skin care',
  'hygiene articles',
  'napkins'],
 ['citrus fruit',
  'curd',
  'pastry',
  'margarine',
  'sugar',
  'candy',
  'newspapers'],
 ['other vegetables',
  'whole milk',
  'bottled water',
  'soda',
  'misc. beverages',
  'bottled beer',
  'red/blush wine',
  'napkins'],
 ['citrus fruit', 'whole milk', 'rolls/buns'],
 ['sausage', 'oil', 'hygiene articles', 'napkins'],
 ['frankfurter',
  'beef',
  'hamburger meat',
  'grapes',
  'root vegetables',
  'whole milk',
  'butter',
  'frozen dessert',
  'potato products',
  'bottled water',
  'bottled beer'],
 ['hard cheese', 'rolls/buns', 'bottled water', 'newspapers'],
 ['cream cheese', 'rolls/buns', 'soda', 'chocolate'],
 ['turkey', 'beef', 'frozen vegetables', 'dishes', 'photo/film'],
 ['pork',
  'other vegetables',
  'whipped/sour cream',
  'rolls/buns',
  'soda',
  'shopping bags'],
 ['whole milk', 'beverages'],
 ['rolls/buns', 'soda'],
 ['sausage',
  'pip fruit',
  'whole milk',
  'curd',
  'yogurt',
  'sliced cheese',
  'rolls/buns',
  'bottled water',
  'hygiene articles'],
 ['ice cream'],
 ['liquor'],
 ['pip fruit', 'other vegetables', 'fruit/vegetable juice'],
 ['root vegetables', 'other vegetables', 'yogurt'],
 ['soda'],
 ['soda'],
 ['sausage',
  'citrus fruit',
  'tropical fruit',
  'other vegetables',
  'whole milk',
  'yogurt',
  'rolls/buns',
  'bottled water',
  'soda',
  'chocolate',
  'newspapers'],
 ['root vegetables', 'whole milk', 'pet care', 'detergent'],
 ['pork',
  'berries',
  'root vegetables',
  'other vegetables',
  'pastry',
  'specialty bar'],
 ['pork'],
 ['chocolate'],
 ['fruit/vegetable juice'],
 ['pickled vegetables', 'coffee'],
 ['bottled water'],
 ['frankfurter',
  'sausage',
  'butter',
  'whipped/sour cream',
  'rolls/buns',
  'margarine',
  'spices'],
 ['tropical fruit',
  'pip fruit',
  'onions',
  'other vegetables',
  'whole milk',
  'domestic eggs',
  'sugar',
  'soups',
  'tea',
  'soda',
  'hygiene articles',
  'napkins'],
 ['canned beer'],
 ['root vegetables'],
 ['meat', 'citrus fruit', 'berries', 'root vegetables', 'whole milk', 'soda'],
 ['frankfurter',
  'rolls/buns',
  'bottled water',
  'fruit/vegetable juice',
  'hygiene articles'],
 ['tropical fruit', 'margarine', 'rum'],
 ['tropical fruit',
  'root vegetables',
  'herbs',
  'whole milk',
  'butter milk',
  'whipped/sour cream',
  'flour',
  'hygiene articles'],
 ['citrus fruit',
  'pip fruit',
  'root vegetables',
  'other vegetables',
  'whole milk',
  'cream cheese',
  'domestic eggs',
  'brown bread',
  'margarine',
  'baking powder',
  'waffles'],
 ['hamburger meat',
  'other vegetables',
  'whole milk',
  'curd',
  'yogurt',
  'rolls/buns',
  'pastry',
  'semi-finished bread',
  'margarine',
  'bottled water',
  'fruit/vegetable juice'],
 ['chicken',
  'pip fruit',
  'other vegetables',
  'whole milk',
  'dessert',
  'yogurt',
  'whipped/sour cream',
  'rolls/buns',
  'pasta',
  'soda',
  'waffles'],
 ['chicken',
  'citrus fruit',
  'tropical fruit',
  'root vegetables',
  'whole milk',
  'frozen fish',
  'rolls/buns'],
 ['frankfurter',
  'citrus fruit',
  'onions',
  'other vegetables',
  'whole milk',
  'rolls/buns',
  'sugar',
  'soda'],
 ['canned beer'],
 ['turkey', 'pip fruit', 'salad dressing', 'pastry'],
 ['packaged fruit/vegetables',
  'whole milk',
  'curd',
  'yogurt',
  'domestic eggs',
  'brown bread',
  'mustard',
  'pickled vegetables',
  'bottled water',
  'misc. beverages'],
 ['pasta'],
 ['citrus fruit', 'tropical fruit'],
 ['sausage',
  'whole milk',
  'yogurt',
  'rolls/buns',
  'brown bread',
  'pot plants'],
 ['whole milk', 'frozen meals', 'pastry', 'fruit/vegetable juice', 'waffles'],
 ['canned beer'],
 ['citrus fruit', 'sugar', 'sauces'],
 ['liquor (appetizer)'],
 ['citrus fruit',
  'other vegetables',
  'rolls/buns',
  'salty snack',
  'shopping bags'],
 ['sausage'],
 ['chicken',
  'other vegetables',
  'whole milk',
  'vinegar',
  'oil',
  'bottled water',
  'canned beer',
  'napkins',
  'newspapers'],
 ['hamburger meat',
  'root vegetables',
  'other vegetables',
  'whole milk',
  'yogurt',
  'whipped/sour cream',
  'specialty cheese',
  'flour',
  'margarine'],
 ['sausage', 'pork', 'other vegetables', 'dessert', 'yogurt', 'oil', 'soda'],
 ['beef',
  'berries',
  'root vegetables',
  'whole milk',
  'whipped/sour cream',
  'abrasive cleaner'],
 ['citrus fruit', 'packaged fruit/vegetables', 'yogurt', 'bottled water'],
 ['UHT-milk', 'coffee'],
 ['candy'],
 ['newspapers'],
 ['beef', 'citrus fruit', 'other vegetables', 'yogurt'],
 ['sausage', 'rolls/buns'],
 ['frankfurter',
  'beef',
  'root vegetables',
  'curd',
  'dessert',
  'yogurt',
  'soft cheese',
  'rolls/buns',
  'mustard',
  'pickled vegetables',
  'canned beer',
  'hygiene articles',
  'napkins'],
 ['canned beer'],
 ['bottled beer'],
 ['onions', 'soda', 'chewing gum', 'chocolate', 'newspapers'],
 ['tropical fruit',
  'packaged fruit/vegetables',

In [9]:
transacciones_encoded.head(10)

,Instant food products,UHT-milk,abrasive cleaner,artif. sweetener,baby cosmetics,baby food,bags,baking powder,bathroom cleaner,beef,...,turkey,vinegar,waffles,whipped/sour cream,whisky,white bread,white wine,whole milk,yogurt,zwieback
0,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,True,False
2,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,True,False,False
3,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,True,False
4,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,True,False,False
5,False,False,True,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,True,True,False
6,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
7,False,True,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
8,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
9,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,True,False,False

In [10]:
# Soporte ???

transacciones_encoded.mean(axis = 0).sort_values(ascending = False).head(15)

whole milk          0.255516
other vegetables    0.193493
rolls/buns          0.183935
soda                0.174377
yogurt              0.139502
bottled water       0.110524
root vegetables     0.108998
tropical fruit      0.104931
shopping bags       0.098526
sausage             0.093950
pastry              0.088968
citrus fruit        0.082766
bottled beer        0.080529
newspapers          0.079817
canned beer         0.077682
dtype: float64

In [11]:
transacciones_encoded.sum(axis = 0).sort_values(ascending = False).head(15)

whole milk          2513
other vegetables    1903
rolls/buns          1809
soda                1715
yogurt              1372
bottled water       1087
root vegetables     1072
tropical fruit      1032
shopping bags        969
sausage              924
pastry               875
citrus fruit         814
bottled beer         792
newspapers           785
canned beer          764
dtype: int64

In [12]:
transacciones_encoded.shape[0]

9835

In [13]:
# Identificación de reglas frecuentes

soporte_min = 30 / transacciones_encoded.shape[0]
print(f"Soporte mínimo: {soporte_min}")
reglas = apriori(transacciones_encoded, min_support = soporte_min, use_colnames = True)
reglas.sort_values(by = "support", ascending = False)

Soporte mínimo: 0.003050330452465684

       support                                          itemsets
133   0.255516                                      (whole milk)
83    0.193493                                (other vegetables)
98    0.183935                                      (rolls/buns)
111   0.174377                                            (soda)
134   0.139502                                          (yogurt)
...        ...                                               ...
1439  0.003050                    (yogurt, butter, citrus fruit)
1601  0.003050                  (coffee, yogurt, tropical fruit)
664   0.003050                              (dessert, margarine)
1884  0.003050                 (whole milk, newspapers, sausage)
1366  0.003050  (shopping bags, bottled water, other vegetables)

[2226 rows x 2 columns]

In [14]:
reglas["n_items"] = reglas["itemsets"].apply(lambda x: len(x))
reglas.query("n_items >= 2").sort_values("support", ascending = False).head(10)

       support                             itemsets  n_items
1076  0.074835       (whole milk, other vegetables)        2
1171  0.056634             (whole milk, rolls/buns)        2
1275  0.056024                 (whole milk, yogurt)        2
1185  0.048907        (whole milk, root vegetables)        2
1055  0.047382  (other vegetables, root vegetables)        2
1077  0.043416           (yogurt, other vegetables)        2
1054  0.042603       (other vegetables, rolls/buns)        2
1263  0.042298         (whole milk, tropical fruit)        2
1240  0.040061                   (whole milk, soda)        2
1161  0.038332                   (soda, rolls/buns)        2

In [15]:
reglas[reglas["n_items"] == 3].sort_values("support", ascending=False)

       support                                         itemsets  n_items
1948  0.023183  (whole milk, other vegetables, root vegetables)        3
1983  0.022267           (whole milk, yogurt, other vegetables)        3
1937  0.017895       (whole milk, other vegetables, rolls/buns)        3
1974  0.017082   (whole milk, other vegetables, tropical fruit)        3
2068  0.015557                 (whole milk, yogurt, rolls/buns)        3
...        ...                                              ...      ...
1376  0.003050               (yogurt, bottled water, pip fruit)        3
1491  0.003050                        (soda, rolls/buns, candy)        3
1379  0.003050       (shopping bags, bottled water, rolls/buns)        3
1964  0.003050        (sliced cheese, yogurt, other vegetables)        3
1884  0.003050                (whole milk, newspapers, sausage)        3

[850 rows x 3 columns]

In [16]:
# Buscar las reglas que tengan a "newspapers"

mask = reglas["itemsets"].map(lambda x: "newspapers" in x)
reglas.loc[mask].sort_values(by = "support", ascending = False)

       support                                           itemsets  n_items
78    0.079817                                       (newspapers)        1
1017  0.027351                           (whole milk, newspapers)        2
1006  0.019725                           (newspapers, rolls/buns)        2
1002  0.019319                     (newspapers, other vegetables)        2
1018  0.015353                               (yogurt, newspapers)        2
...        ...                                                ...      ...
1876  0.003050                  (newspapers, rolls/buns, sausage)        3
1884  0.003050                  (whole milk, newspapers, sausage)        3
957   0.003050                                 (meat, newspapers)        2
896   0.003050                     (newspapers, hygiene articles)        2
2171  0.003050  (whole milk, newspapers, other vegetables, roo...        4

[80 rows x 3 columns]

In [17]:
# Identificación de itemsets frecuentes

soporte_min_ = 30 / transacciones_encoded.shape[0]
reglas_frecuentes = apriori(transacciones_encoded, min_support = soporte_min_, use_colnames = True)

# Crear reglas de associación (confianza mínima del 70%)

confianza = 0.7 # confianza mínima del 70% para que una regla sea selecionada
reglas_1 = association_rules(reglas_frecuentes, metric = "confidence", min_threshold = confianza)
print(f"Número de reglas generadas: {len(reglas_1)}")
reglas_1.sort_values(by = "support", ascending = False).head(20)

Número de reglas generadas: 19

,antecedents,consequents,antecedent support,consequent support,support,confidence,lift,leverage,conviction,zhangs_metric
14,"(yogurt, root vegetables, tropical fruit)",(whole milk),0.008134,0.255516,0.005694,0.700000,2.739554,0.003616,2.481613,0.640185
2,"(butter, curd)",(whole milk),0.006812,0.255516,0.004881,0.716418,2.803808,0.003140,2.625286,0.647755
5,"(domestic eggs, curd)",(whole milk),0.006507,0.255516,0.004779,0.734375,2.874086,0.003116,2.802763,0.656334
10,"(tropical fruit, root vegetables, citrus fruit)",(other vegetables),0.005694,0.193493,0.004474,0.785714,4.060694,0.003372,3.763701,0.758053
15,"(yogurt, whipped/sour cream, tropical fruit)",(whole milk),0.006202,0.255516,0.004372,0.704918,2.758802,0.002787,2.522974,0.641503
11,"(yogurt, curd, tropical fruit)",(whole milk),0.005287,0.255516,0.003965,0.750000,2.935237,0.002614,2.977936,0.662816
4,"(butter, pork)",(whole milk),0.005491,0.255516,0.003864,0.703704,2.754049,0.002461,2.512633,0.640415
18,"(yogurt, other vegetables, root vegetables, tr...",(whole milk),0.004982,0.255516,0.003559,0.714286,2.795464,0.002286,2.605694,0.645494
6,"(domestic eggs, sugar)",(whole milk),0.004982,0.255516,0.003559,0.714286,2.795464,0.002286,2.605694,0.645494
12,"(domestic eggs, other vegetables, whipped/sour...",(whole milk),0.005084,0.255516,0.003559,0.700000,2.739554,0.002260,2.481613,0.638222
13,"(whipped/sour cream, root vegetables, tropical...",(other vegetables),0.004575,0.193493,0.003355,0.733333,3.789981,0.002470,3.024403,0.739530
9,"(yogurt, butter, tropical fruit)",(whole milk),0.004575,0.255516,0.003355,0.733333,2.870009,0.002186,2.791815,0.654564
1,"(coffee, butter)",(whole milk),0.004779,0.255516,0.003355,0.702128,2.747881,0.002134,2.499339,0.639138
0,"(baking powder, yogurt)",(whole milk),0.004575,0.255516,0.003254,0.711111,2.783039,0.002085,2.577060,0.643626
7,"(other vegetables, brown bread, root vegetables)",(whole milk),0.004067,0.255516,0.003152,0.775000,3.033078,0.002113,3.308818,0.673039
16,"(whole milk, tropical fruit, root vegetables, ...",(other vegetables),0.003559,0.193493,0.003152,0.885714,4.577509,0.002463,7.056940,0.784332
17,"(tropical fruit, other vegetables, root vegeta...",(whole milk),0.004474,0.255516,0.003152,0.704545,2.757344,0.002009,2.519792,0.640196
8,"(yogurt, butter, root vegetables)",(whole milk),0.003864,0.255516,0.003050,0.789474,3.089723,0.002063,3.536299,0.678970
3,"(onions, butter)",(whole milk),0.004067,0.255516,0.003050,0.750000,2.935237,0.002011,2.977936,0.662004

In [18]:
# Seleccionar reglas que tienen "other vegetables" en el consecuente

mask_1 = reglas_1["consequents"].map(lambda x: "other vegetables" in x)
reglas_1.loc[mask_1]

,antecedents,consequents,antecedent support,consequent support,support,confidence,lift,leverage,conviction,zhangs_metric
10,"(tropical fruit, root vegetables, citrus fruit)",(other vegetables),0.005694,0.193493,0.004474,0.785714,4.060694,0.003372,3.763701,0.758053
13,"(whipped/sour cream, root vegetables, tropical...",(other vegetables),0.004575,0.193493,0.003355,0.733333,3.789981,0.002470,3.024403,0.739530
16,"(whole milk, tropical fruit, root vegetables, ...",(other vegetables),0.003559,0.193493,0.003152,0.885714,4.577509,0.002463,7.056940,0.784332