### Modelos de Machine Learning
* Arboles de Decision Clasificación
* Bosques Aleatorios Clasificación
* Analisis de Componentes Principales
* Analisis de Clusters
* Analisis Discriminante
* XGBoost
* Introduccion a las Redes Neuronales

In [1]:
import pandas as pd

In [ ]:
clasificacion = pd.read_csv("./Data/ML-MATT-CompetitionQT2021_train.csv", sep = ";")
clasificacion.head()

,Time,CellName,PRBUsageUL,PRBUsageDL,meanThr_DL,meanThr_UL,maxThr_DL,maxThr_UL,meanUE_DL,meanUE_UL,maxUE_DL,maxUE_UL,maxUE_UL+DL,Unusual
0,10:45,3BLTE,12.3848,1.4019,0.3927,0.0438,16.6522,0.6806,1.1293,1.0491,5,3,8,1
1,9:45,1BLTE,22.0438,2.0016,0.5620,0.2697,10.3994,1.1771,1.4480,1.1630,6,5,11,1
2,7:45,9BLTE,0.5105,0.4258,0.0152,0.0106,0.2755,0.1685,1.0379,1.0535,1,2,3,1
3,2:45,4ALTE,1.9963,1.1513,0.9908,0.0245,64.7465,0.8747,1.0766,1.0526,3,2,5,1
4,3:30,10BLTE,0.3030,0.4040,0.0160,0.0130,0.3480,0.1680,1.0110,1.0110,2,1,3,0

In [4]:
data = clasificacion[['PRBUsageUL', 'PRBUsageDL', 'meanThr_DL',
       'meanThr_UL', 'maxThr_DL', 'maxThr_UL', 'meanUE_DL', 'meanUE_UL',
       'maxUE_DL', 'maxUE_UL', 'maxUE_UL+DL', 'Unusual']]
data.head()

,PRBUsageUL,PRBUsageDL,meanThr_DL,meanThr_UL,maxThr_DL,maxThr_UL,meanUE_DL,meanUE_UL,maxUE_DL,maxUE_UL,maxUE_UL+DL,Unusual
0,12.3848,1.4019,0.3927,0.0438,16.6522,0.6806,1.1293,1.0491,5,3,8,1
1,22.0438,2.0016,0.5620,0.2697,10.3994,1.1771,1.4480,1.1630,6,5,11,1
2,0.5105,0.4258,0.0152,0.0106,0.2755,0.1685,1.0379,1.0535,1,2,3,1
3,1.9963,1.1513,0.9908,0.0245,64.7465,0.8747,1.0766,1.0526,3,2,5,1
4,0.3030,0.4040,0.0160,0.0130,0.3480,0.1680,1.0110,1.0110,2,1,3,0

In [5]:
x_data = data[['PRBUsageUL', 'PRBUsageDL', 'meanThr_DL',
       'meanThr_UL', 'maxThr_DL', 'maxThr_UL', 'meanUE_DL', 'meanUE_UL',
       'maxUE_DL', 'maxUE_UL', 'maxUE_UL+DL']]

In [6]:
y_data = data["Unusual"]

In [7]:
from sklearn.model_selection import train_test_split

x_train, x_test, y_train, y_test = train_test_split(x_data, y_data, test_size = 0.2, random_state = 2024)

### Arboles de Decision Clasificación

* Tipo de Aprendizaje = Supervisado
* Tipo de Problema a resolver = predictivo categórico
* Parametros = No hay
* Hiperparámetros = criterio de separacion, estrategia de division, profundidad del arbol

![AD](https://i.ytimg.com/vi/NdFZSkWj4Ko/maxresdefault.jpg)

In [8]:
from sklearn.tree import DecisionTreeClassifier

In [9]:
arb_dec_cla = DecisionTreeClassifier(criterion = "gini", splitter = "best", max_depth = 15, random_state = 500)
arb_dec_cla.fit(x_train, y_train)

DecisionTreeClassifier(max_depth=15, random_state=500)

In [10]:
y_pred_adc = arb_dec_cla.predict(x_test)
y_pred_adc

array([1, 0, 0, ..., 1, 0, 1], dtype=int64)

In [11]:
from sklearn.metrics import confusion_matrix
from sklearn.metrics import accuracy_score
from sklearn.metrics import precision_score
from sklearn.metrics import recall_score
from sklearn.metrics import f1_score

print(confusion_matrix(y_test, y_pred_adc))
print(accuracy_score(y_test, y_pred_adc))
print(precision_score(y_test, y_pred_adc))
print(recall_score(y_test, y_pred_adc))
print(f1_score(y_test, y_pred_adc))

[[5350   70]
 [ 316 1645]]
0.947703563202818
0.9591836734693877
0.8388577256501785
0.8949945593035907

In [ ]:
# Algoritmo Naive-Bayes 0.515
# Maquina de Vectores de Soporte 0.734
# K vecinos más cercanos 0.753
# Regresion Logistica 0.734

### Bosques Aleatorios Clasificación

* Tipo de Aprendizaje = Supervisado
* Tipo de Problema a resolver = predictivo categórico
* Parametros = No hay
* Hiperparámetros = criterio de separacion, estrategia de division, profundidad del arbol, número de arboles, estrategia de seleccion

![BA](https://th.bing.com/th/id/OIP.UGG7CTJXGea5bRIyMChvwAAAAA?pid=ImgDet&rs=1)

In [12]:
from sklearn.ensemble import RandomForestClassifier

In [13]:
bosq_ale_cla = RandomForestClassifier(n_estimators = 10, criterion = "gini", max_depth = 15, random_state = 543)
bosq_ale_cla.fit(x_train, y_train)

RandomForestClassifier(max_depth=15, n_estimators=10, random_state=543)

In [14]:
y_pred_bac = bosq_ale_cla.predict(x_test)
y_pred_bac

array([1, 0, 0, ..., 1, 0, 1], dtype=int64)

In [15]:
print(confusion_matrix(y_test, y_pred_bac))
print(accuracy_score(y_test, y_pred_bac))
print(precision_score(y_test, y_pred_bac))
print(recall_score(y_test, y_pred_bac))
print(f1_score(y_test, y_pred_bac))

[[5350   70]
 [ 444 1517]]
0.93036173960168
0.9558916194076874
0.7735849056603774
0.855129650507328

### Analisis de Componentes Principales

* Tipo de Aprendizaje = No Supervisado
* Tipo de Problema a resolver = predictivo númerico y categórico
* Parametros = Componentes Principales
* Hiperparámetros = No hay

![ACP](https://3.bp.blogspot.com/-YfV5P_qZ-5M/V3iF0Fm0N6I/AAAAAAAAD9g/XT5r1mNt8oE54atyJ4048YDftSPiNjG6gCLcB/s1600/pca2.png)

In [16]:
from sklearn.decomposition import PCA

In [17]:
data.shape

(36904, 12)

In [18]:
ana_comp_pri = PCA(n_components = 3)
ana_comp_pri.fit_transform(data)

array([[  0.07261079,   4.57250429,  -1.28826436],
       [ -2.27441244,  16.4131716 ,  -0.71723041],
       [-19.77873032,  -2.36065155,   0.67401472],
       ...,
       [ -6.12687234,  -1.15181814,  -0.64814903],
       [ 11.41680343,   1.9991724 ,  -2.28861333],
       [ 63.41866247,  -7.39373204,  -8.30244961]])

In [21]:
type(ana_comp_pri)

sklearn.decomposition._pca.PCA

In [22]:
ana_comp_pri.components_

array([[ 3.00364017e-01,  6.84383281e-02,  2.93528986e-02,
         2.72980556e-03,  9.34333370e-01,  1.13551373e-01,
         6.52710597e-03,  6.41508542e-03,  6.21352594e-02,
         4.79203376e-02,  1.10055597e-01, -1.64568623e-03],
       [ 8.94418456e-01,  7.24716903e-02,  1.29365391e-02,
         4.75045930e-03, -3.36267533e-01,  1.55268533e-02,
         1.39561533e-02,  3.57480757e-02,  1.17040390e-01,
         1.13550215e-01,  2.30590606e-01, -4.44864634e-03],
       [-4.77345062e-02,  6.35395187e-02,  4.10580749e-02,
         1.34305794e-02, -1.04444564e-01,  9.89241320e-01,
        -2.42852118e-03, -2.08129981e-02, -1.92730425e-02,
        -1.59961488e-02, -3.52691913e-02,  7.89523095e-04]])

In [23]:
ana_comp_pri.explained_variance_ratio_

array([0.75861204, 0.15470668, 0.06112026])

In [24]:
ana_comp_pri.explained_variance_ratio_.sum()

0.9744389829268253

### Determinacion del número de Grupos

![Codo_de_Jambu](https://i.ytimg.com/vi/3NquQS22Q88/hqdefault.jpg)

In [25]:
import plotly.express as px
import numpy as np
from sklearn.cluster import KMeans

In [27]:
grupos = []

for i in range(1, 12):
    kmeans = KMeans(n_clusters = i, max_iter = 300)
    kmeans.fit(x_data)
    grupos.append(kmeans.inertia_)

df = pd.DataFrame({"n_cluster": range(1, 12), "calculo": grupos})
px.line(df, x = "n_cluster", y = "calculo")

AttributeError: 'NoneType' object has no attribute 'split'

### Analisis de Clusters

* Tipo de Aprendizaje = No Supervisado
* Tipo de Problema a resolver = predictivo númerico y categórico
* Parametros = No hay
* Hiperparámetros = Tipo de distancia

![AC](https://www.researchgate.net/profile/Marcos-Lujan-3/publication/317529339/figure/download/fig3/AS:504425715126275@1497275870249/Figura-3-Analisis-Cluster-para-la-identificacion-de-especies-de-liquenes-sensibles-y.png)

In [28]:
from sklearn.cluster import AgglomerativeClustering

ana_clu = AgglomerativeClustering(n_clusters = 2, affinity = "euclidean")
ana_clu.fit(x_test)

AgglomerativeClustering()

In [29]:
ana_clu.fit_predict(x_test)

array([0, 1, 1, ..., 0, 0, 0], dtype=int64)

### Analisis Discriminante

* Tipo de Aprendizaje = No Supervisado
* Tipo de Problema a resolver = predictivo númerico y categórico
* Parametros = Máximizar
* Hiperparámetros = No hay

![AD](https://th.bing.com/th/id/OIP.2HL4fF0kDq-a2lorhH2AkAAAAA?pid=ImgDet&rs=1)

In [30]:
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis as LDA

In [31]:
ana_disc = LDA()
ana_disc.fit(x_train, y_train)

LinearDiscriminantAnalysis()

In [32]:
x_da = ana_disc.predict(x_test)
x_da

array([0, 0, 0, ..., 0, 0, 0], dtype=int64)

In [33]:
type(x_da)

numpy.ndarray

### XGBoost

* Tipo de Aprendizaje = Supervisado
* Tipo de Problema a resolver = predictivo númerico y categórico
* Parametros = No hay
* Hiperparámetros = Arboles iniciales

![XGB](https://www.researchgate.net/profile/Niaz-Shahani-2/publication/359380024/figure/fig13/AS:1136660276363275@1648012336208/The-general-structure-of-XGBoost-model.png)

![XGBoost](https://miro.medium.com/v2/resize:fit:1104/1*9BowVV2E_LctnBrU6ZJw4A.jpeg)

In [34]:
from xgboost import XGBRegressor

In [35]:
from xgboost import XGBClassifier

In [36]:
xgboost = XGBClassifier()
xgboost.fit(x_train, y_train)

XGBClassifier(base_score=0.5, booster='gbtree', callbacks=None,
              colsample_bylevel=1, colsample_bynode=1, colsample_bytree=1,
              early_stopping_rounds=None, enable_categorical=False,
              eval_metric=None, feature_types=None, gamma=0, gpu_id=-1,
              grow_policy='depthwise', importance_type=None,
              interaction_constraints='', learning_rate=0.300000012,
              max_bin=256, max_cat_threshold=64, max_cat_to_onehot=4,
              max_delta_step=0, max_depth=6, max_leaves=0, min_child_weight=1,
              missing=nan, monotone_constraints='()', n_estimators=100,
              n_jobs=0, num_parallel_tree=1, predictor='auto', random_state=0, ...)

In [37]:
y_pred_xgb = xgboost.predict(x_test)
y_pred_xgb

array([1, 0, 0, ..., 1, 0, 1])

In [38]:
type(y_pred_xgb)

numpy.ndarray

In [39]:
print(confusion_matrix(y_test, y_pred_xgb))
print(accuracy_score(y_test, y_pred_xgb))
print(precision_score(y_test, y_pred_xgb))
print(recall_score(y_test, y_pred_xgb))
print(f1_score(y_test, y_pred_xgb))

[[5417    3]
 [  98 1863]]
0.986316217314727
0.9983922829581994
0.9500254971953085
0.9736085706819962